### ISSUE TITLE
START gets defined as COIN B

### ISSUE THREAD

**Issue by carlff** [va7deo/zerowing#15]
After defining buttons in the OSD, the button chosen for START instead becomes COIN B (can be seen in the Zero Wing input test). The game can't be started.

**Comment by thehughhefner** [comment]
I did a pull request fixing this issue with zero wing. My GitHub is buggy for some reason. You need to remove the - in buttons in order for it to work

**Comment by blackwine** [comment]
All MRAs are valid for the current code in the repository. There is a problem when you use updated MRA with latest rbf which doesn't incude patch for the third (unused) button support. It will get fixed when new rbf build will go live.
