### ISSUE TITLE
Flip screen dip switch doesn't take effect (even after restart)

### ISSUE THREAD

**Issue by felleg** [va7deo/zerowing#18]
Tested on Tatsujin with zerowing_u20220205.rbf (source: https://misterfpga.org/viewtopic.php?f=25&start=60&t=4034&sid=f84131bcd6bb9578848ec9f5623982b6)

**Comment by va7deo** [comment]
It's not implemented yet as stated in the readme.

**Comment by va7deo** [comment]
Screen flip / cocktail mode is now supported
