### ISSUE TITLE
Use submodules

### ISSUE THREAD

**Issue by jotego** [va7deo/zerowing#35]
I recommend using a submodule for both JTOPL and FX68K. That way we can keep track of changes in all repositories. People didn't do that with JT12 in MiSTer and created confusion that has lasted a few years now.
If you are afraid of the original JTOPL repo going away, make a fork and make the submodule point to your fork. You will still be able to PR to the original repo.

**Comment by va7deo** [comment]
That's a good idea.  I'll fork the cores and make them submodules.
