### ISSUE TITLE
Tatsujin Oh / Truxton 2 Audio Issue

### ISSUE THREAD

**Issue by Disciple1982** [va7deo/zerowing#42]
Hello,

Just wanted to throw a heads up out there. The Truxton 2 core has an issue with the audio where the enemy ship explosion sound effects are almost nonexistent. It's very noticeable when comparing the Mister core gameplay to other gameplay online. 

Just a heads up! Thanks!

**Comment by atrac17** [comment]
Wrong repository.

https://github.com/atrac17/Toaplan2
